# vim: ts=2 sw=2 et :
---
language: python

jobs:
  include:
    - MOLECULE_DISTRO: centos8
      MOLECULE_DOCKER_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu2004
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd
    - MOLECULE_DISTRO: debian10
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd

sudo: required

services:
  - docker

install:
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
