---
- name: Converge
  hosts: all
  roles:
    - nephelaiio.docker
  pre_tasks:
    - name: Update apt package cache
      apt:
        package: gpg-agent
        update_cache: true
      when: ansible_os_family == 'Debian'

  post_tasks:
    - name: Install python3 binary redirection
      apt:
        name: python-is-python3
      when: ansible_os_family == 'Debian'
