---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-install
    image: geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
verifier:
  name: ansible
