---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: docker-${MOLECULE_SCENARIO_NAME}-daemon
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - docker
  - name: docker-${MOLECULE_SCENARIO_NAME}-proxy
    image: "${MOLECULE_KVM_IMAGE}"
    groups:
      - mirror
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify.yml
  inventory:
    hosts:
      all:
        vars:
          ansible_ssh_extra_args: "-o ControlPersist=no -o ControlPath=none"
          libvirt_user: molecule
          libvirt_address: '172.31.252.1/24'
          libvirt_platforms: "{{ molecule_yml.platforms }}"
          docker_conf_mirrors: "{{ groups['mirror'] }}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
