---
- name: Verify
  hosts: all
  vars:
    docker_service: docker.service
  pre_tasks:
    - name: Verify Docker cli is installed
      ansible.builtin.command: "docker --version"
      changed_when: false

    - name: Verify Docker pip is installed
      ansible.builtin.command: "python3 -c 'import docker'"
      changed_when: false

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check service definition
      ansible.builtin.assert:
        that: docker service is available
      when: docker_service not in ansible_facts.services

    - name: Check service running state
      ansible.builtin.assert:
        that: docker service is running
      when: ansible_facts.services[docker_service].state != "running"

    - name: Check service startup state
      ansible.builtin.assert:
        that: docker service is running
      when: ansible_facts.services[docker_service].status != "enabled"

    - name: Run sample Docker container
      community.docker.docker_container:
        name: hello
        image: hello-world
