---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  run yamllint .
  run ansible-lint .
