---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: centos7
    image: centos:7
    privileged: True
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: centos8
    image: centos:8
    privileged: True
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: stretch
    image: debian:stretch
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: xenial
    image: ubuntu:xenial
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: bionic
    image: ubuntu:bionic
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: focal
    image: ubuntu:focal
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
verifier:
  name: testinfra
